-- Baseline schema for validate + Flyway.
-- Mirrors the JPA entities. Idempotent: safe on DBs previously created by ddl-auto: update.
-- Spring naming strategy: camelCase -> snake_case (categoryId -> category_id, imageUrl -> image_url).

CREATE TABLE IF NOT EXISTS category (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    icon_url VARCHAR(255),
    parent_category_id BIGINT
);

CREATE TABLE IF NOT EXISTS exercise (
    exercise_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS exercise_instruction (
    instruction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "text" VARCHAR(255),
    position INTEGER,
    exercise_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS exercise_image (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url VARCHAR(255) NOT NULL,
    position INTEGER,
    exercise_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS exercise_category (
    exercise_category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL
);

-- Unique constraint from ExerciseCategoryEntity
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk_exercise_category_exercise_id_category_id') THEN
        ALTER TABLE exercise_category
            ADD CONSTRAINT uk_exercise_category_exercise_id_category_id UNIQUE (exercise_id, category_id);
    END IF;
END $$;

-- Foreign keys (Hibernate would have created these under ddl-auto: update)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_exercise_instruction_exercise') THEN
        ALTER TABLE exercise_instruction
            ADD CONSTRAINT fk_exercise_instruction_exercise FOREIGN KEY (exercise_id) REFERENCES exercise (exercise_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_exercise_image_exercise') THEN
        ALTER TABLE exercise_image
            ADD CONSTRAINT fk_exercise_image_exercise FOREIGN KEY (exercise_id) REFERENCES exercise (exercise_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_exercise_category_exercise') THEN
        ALTER TABLE exercise_category
            ADD CONSTRAINT fk_exercise_category_exercise FOREIGN KEY (exercise_id) REFERENCES exercise (exercise_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_exercise_category_category') THEN
        ALTER TABLE exercise_category
            ADD CONSTRAINT fk_exercise_category_category FOREIGN KEY (category_id) REFERENCES category (category_id);
    END IF;
END $$;

-- Indexes for join/filter columns (FK indexes + plain parent_category_id which has no FK constraint)
CREATE INDEX IF NOT EXISTS idx_exercise_instruction_exercise_id ON exercise_instruction (exercise_id);
CREATE INDEX IF NOT EXISTS idx_exercise_image_exercise_id ON exercise_image (exercise_id);
CREATE INDEX IF NOT EXISTS idx_exercise_category_exercise_id ON exercise_category (exercise_id);
CREATE INDEX IF NOT EXISTS idx_exercise_category_category_id ON exercise_category (category_id);
CREATE INDEX IF NOT EXISTS idx_category_parent_category_id ON category (parent_category_id);
