-- V2: migrate databases created under the old exercise model
-- (exercise.image_url + exercise.category_id columns, no child tables)
-- to the current model (exercise_image / exercise_instruction / exercise_category).
-- Every step is guarded: safe on fresh V1 databases (old columns absent)
-- and on baselined databases where V1 tables were never created.

-- 1. New tables (same definitions as V1, idempotent for baselined DBs)
CREATE TABLE IF NOT EXISTS exercise_instruction (
    instruction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "text" VARCHAR(255),
    position INTEGER,
    exercise_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS exercise_image (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url VARCHAR(255) NOT NULL,
    position INTEGER,
    exercise_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS exercise_category (
    exercise_category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk_exercise_category_exercise_id_category_id') THEN
        ALTER TABLE exercise_category
            ADD CONSTRAINT uk_exercise_category_exercise_id_category_id UNIQUE (exercise_id, category_id);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_exercise_instruction_exercise') THEN
        ALTER TABLE exercise_instruction
            ADD CONSTRAINT fk_exercise_instruction_exercise FOREIGN KEY (exercise_id) REFERENCES exercise (exercise_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_exercise_image_exercise') THEN
        ALTER TABLE exercise_image
            ADD CONSTRAINT fk_exercise_image_exercise FOREIGN KEY (exercise_id) REFERENCES exercise (exercise_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_exercise_category_exercise') THEN
        ALTER TABLE exercise_category
            ADD CONSTRAINT fk_exercise_category_exercise FOREIGN KEY (exercise_id) REFERENCES exercise (exercise_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_exercise_category_category') THEN
        ALTER TABLE exercise_category
            ADD CONSTRAINT fk_exercise_category_category FOREIGN KEY (category_id) REFERENCES category (category_id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_exercise_instruction_exercise_id ON exercise_instruction (exercise_id);
CREATE INDEX IF NOT EXISTS idx_exercise_image_exercise_id ON exercise_image (exercise_id);
CREATE INDEX IF NOT EXISTS idx_exercise_category_exercise_id ON exercise_category (exercise_id);
CREATE INDEX IF NOT EXISTS idx_exercise_category_category_id ON exercise_category (category_id);

-- 2. Move data from old columns into the new tables (only where old columns exist)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'exercise' AND column_name = 'image_url') THEN
        INSERT INTO exercise_image (image_url, position, exercise_id)
        SELECT e.image_url, 1, e.exercise_id
        FROM exercise e
        WHERE e.image_url IS NOT NULL
        AND NOT EXISTS (SELECT 1 FROM exercise_image i WHERE i.exercise_id = e.exercise_id);
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'exercise' AND column_name = 'category_id') THEN
        INSERT INTO exercise_category (exercise_id, category_id)
        SELECT e.exercise_id, e.category_id
        FROM exercise e
        WHERE e.category_id IS NOT NULL
        AND NOT EXISTS (
            SELECT 1 FROM exercise_category c
            WHERE c.exercise_id = e.exercise_id AND c.category_id = e.category_id
        );
    END IF;
END $$;

-- 3. Drop old columns (data already moved above, same transaction).
-- FK constraint names are Hibernate-generated and differ per database, so drop them dynamically.
DO $$
DECLARE
    r RECORD;
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'exercise' AND column_name = 'category_id') THEN
        FOR r IN
            SELECT conname FROM pg_constraint
            WHERE conrelid = 'exercise'::regclass AND contype = 'f'
        LOOP
            EXECUTE 'ALTER TABLE exercise DROP CONSTRAINT ' || quote_ident(r.conname);
        END LOOP;
        ALTER TABLE exercise DROP COLUMN category_id;
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'exercise' AND column_name = 'image_url') THEN
        ALTER TABLE exercise DROP COLUMN image_url;
    END IF;
END $$;

-- 4. Align nullability with the entity (name is NOT NULL, old DBs allowed NULL)
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'category' AND column_name = 'name' AND is_nullable = 'YES'
    ) AND NOT EXISTS (SELECT 1 FROM category WHERE name IS NULL) THEN
        ALTER TABLE category ALTER COLUMN name SET NOT NULL;
    END IF;
END $$;
